CREATE DATABASE TIPOFRONT_PROJETO_ROMAN;

USE TIPOFRONT_PROJETO_ROMAN;

CREATE TABLE USUARIOS(
	ID INT PRIMARY KEY IDENTITY,
	EMAIL VARCHAR(200) NOT NULL,
	SENHA VARCHAR(200) NOT NULL,
	EQUIPE INT NOT NULL,
	CONSTRAINT EQUIPEVALIDA CHECK(EQUIPE < 5 AND EQUIPE > 0)
);

CREATE TABLE TEMAS(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(200) NOT NULL,
	ATIVO BIT DEFAULT(1)
);

CREATE TABLE PROJETOS(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(200) NOT NULL,
	IDTEMA INT FOREIGN KEY REFERENCES TEMAS(ID) NOT NULL,
	ATIVO  BIT DEFAULT(1) 
);
